# Generated by Django 5.2.8 on 2025-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=10, unique=True, verbose_name='Kode Mata Kuliah')),
                ('nama_mk', models.CharField(max_length=100, verbose_name='Nama Mata Kuliah')),
                ('sks', models.IntegerField(verbose_name='Jumlah SKS')),
                ('dosen', models.CharField(max_length=100, verbose_name='Dosen Pengampu')),
            ],
        ),
    ]
