# Generated by Django 5.2.8 on 2025-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='dosen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='kode_mk',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mk',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(),
        ),
    ]
