# Generated by Django 5.2.8 on 2025-11-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_mahasiswa_alter_matakuliah_dosen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('nilai', models.CharField(blank=True, max_length=2, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs', to='akademik.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs', to='akademik.matakuliah')),
            ],
        ),
    ]
