# Generated by Django 5.2.8 on 2025-11-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_krs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah'),
        ),
        migrations.AlterField(
            model_name='krs',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
