# Generated by Django 5.2.8 on 2025-11-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_alter_krs_mata_kuliah_alter_krs_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('nilai', models.CharField(blank=True, max_length=2, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs', to='akademik.mahasiswa')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='akademik.matakuliah')),
            ],
        ),
        migrations.DeleteModel(
            name='KRS',
        ),
    ]
