# Generated by Django 5.2.8 on 2025-11-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_alter_mahasiswa_nim_pendaftaran_delete_krs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nilai',
        ),
    ]
